### ISSUE TITLE
提示词功能

### ISSUE THREAD

**Issue by darkSuperman** [thep0y/ChatGPT#6]
能不能加一个提示词功能，可以拉取promtp配置，然后输入框输入斜杠就可以匹配相关提示词。就像这个地址一样，你去看看
https://chatbot.theb.ai/#/chat/1002

![image](https://user-images.githubusercontent.com/23699296/234450604-9eb733bf-d9ec-45ac-8814-b191c4c99d59.png)
![image](https://user-images.githubusercontent.com/23699296/234450703-e6ede917-409b-47fc-9818-5a19c0eef553.png)

**Comment by thep0y** [comment]
你指的这个应该是 system 角色设定，我会考虑内置或导入一些已有的角色设定 prompt。
